### ISSUE TITLE
How long will it take to release the official version？

### ISSUE THREAD

**Issue by bnuzhouwei** [DigitalChinaOpenSource/TiDB-for-PostgreSQL#4]
Many systems are built on postgres, mssql, and db2. Their all have database, schema, table lalyer.

It is hard to do migration many applications to TiDB for it lack of the schema layer.

Does this project has timeline that support main feature of postgres that build a release version?

**Comment by pupillord** [comment]
Yes, many systems have such problems in database migration. That is why we begin this project. To accelerate the development and release, we are trying to call for community engineers. Contributions are greatly appreciated and welcomed.
