### ISSUE TITLE
Support for Postgres transaction syntax in Parser

### ISSUE THREAD

**Issue by AmoebaProtozoa** [DigitalChinaOpenSource/TiDB-for-PostgreSQL#41]
### Description
The SQL standard syntax for starting a transaction is `START TRANSACTION`, which both MySQL and PostgreSQL supports. 
They also support syntax like `START TRANSACTION + [modifier]`, where modifier can be `READ WRITE`, `READ ONLY`, etc.
For the ease of use, they also support use `BEGIN` instead of `START TRANSACTION`
However, they treat `BEGIN + [modifier]` differently. (like `BEGIN READ WRITE`)

In Postgres this is completely fine, `BEGIN`/`BEGIN WORK`/`BEGIN TRANSACTION` are all treated as aliases for `START TRANSACTION`

MySQL, on the other hand, does not allow modifier after `BEGIN`, a limitation which TiDB inherits.

In TiDB, the standard way to start new transaction via go code is 

> `txn, err := db.Begin()`

which calls underlying `go-mysql-driver` via go's `database` module, and return a transaction handle (the `txn` above).
After we switch the driver from `lib/pq`, because `pq` starts transaction by `BEGIN READ WRITE` when no modifier provided, it will cause parser to complain.
<img width="399" alt="image" src="https://user-images.githubusercontent.com/8039876/129524793-30ae70e2-19d5-43fa-8759-f5e91df5d90c.png">

Previously in unit tests fixing, we have been solving the problem by skipping `Begin()`method and execute SQL statement `START TRANSACTION;` and execute `COMMIT;` at the end of query block. But since we are not using `Begin()`, we can't get `txn` handle. It will cause problem when multiple transactions are nested or intersected. 

The ideal solution is for parser to support `begin + modifier` syntax.

### References
[PostgreSQL: Documentation: 9.1: BEGIN](https://www.postgresql.org/docs/9.1/sql-begin.html)
[MySQL :: MySQL 8.0 Reference Manual :: 13.3.1 START TRANSACTION, COMMIT, and ROLLBACK Statements](https://dev.mysql.com/doc/refman/8.0/en/commit.html)
[MySQL Difference between BEGIN and START TRANSACTION - Database Administrators Stack Exchange](https://dba.stackexchange.com/questions/261194/mysql-difference-between-begin-and-start-transaction)

**Comment by RogueJin** [comment]
it should update dcparser firstly to understand pg transaction syntax.
https://github.com/DigitalChinaOpenSource/DCParser

**Comment by AmoebaProtozoa** [comment]
The corresponding issue can be find under DCParser
https://github.com/DigitalChinaOpenSource/DCParser/issues/20
