### ISSUE TITLE
Guidelines for contribution to Schema structure?

### ISSUE THREAD

**Issue by RogueJin** [DigitalChinaOpenSource/TiDB-for-PostgreSQL#5]
I would like to help on Schema structure, is there any guidelines to let me how I can start the work?

**Comment by pupillord** [comment]
Hi RogueJin, you can refer to the contribution guide.
> https://github.com/pingcap/community/blob/master/contributors/README.md
This project comes from tidb, and you can use its documentation.

If you just want to complete a simple feature, you can submit the pull request after enough comments and unit test.
